services:
  db:
    image: postgres:17-alpine
    container_name: translation-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: translation_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d translation_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Translation.API/Dockerfile
      args:
        - BUILD_CONFIGURATION=Debug
    container_name: translation-service
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=translation_db;Username=myuser;Password=mypassword
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/src # Syncs code for debugging and migration application

volumes:
  postgres_data:
